version: '3'

services:

   wkspace:
      build:
         context: i/wkspace
         dockerfile: Dockerfile
         args:
            USERNAME: ${USERNAME}
            UPASSWD: ${UPASSWD}
      env_file: .env
      volumes:
         - wkspace:/wkspace
      command: /bin/sh -c "while sleep 1000; do :; done"

networks:
   frontend:
   backend:

volumes:
   wkspace:
