version: '3'

services:

   wkspace:
      build:
         context: i/wkspace
         dockerfile: Dockerfile
         args:
            USERNAME: ${USERNAME}
            UPASSWD: ${UPASSWD}
            VARIANT: ${VARIANT}
      env_file: .env
      volumes:
         - wkspace:${WORKDIR:-'/wkspace'}
networks:
   frontend:
   backend:

volumes:
   wkspace:
